############################################################
##
## S3011 Perennial Sorghum GWAS Pipeline
##
## Script 10: Haplotype / Multilocus Dosage-Profile Analysis
##
## Purpose:
##   - Construct local multilocus dosage profiles from markers in
##     LD with each rhizome GWAS lead SNP
##   - Test profile associations with accession-level rhizome and
##     overwinter-regrowth BLUPs while adjusting for PC1-PC3
##   - Integrate profile classes with the 500-kb ancestry-proxy
##     values generated by Script 08
##   - Summarize profile carriers, trait means, and candidate
##     founder accessions
##   - Generate lead-SNP and multilocus-profile effect figures
##
## Important interpretation:
##   Accession-level genotypes are mean allele dosages and are not
##   phased haplotypes. The profile labels generated here are
##   operational multilocus dosage classes. They are retained under
##   the familiar term "haplotype analysis" for consistency with the
##   manuscript workflow, but they should not be interpreted as
##   experimentally phased chromosomal haplotypes.
##
## Required preceding scripts:
##   00_setup.R
##   01_genotype_QC.R
##   02_aggregate_accession_genotypes.R
##   03_BLUP_estimation.R
##   04_GWAS.R
##   05_marker_based_genome_scan.R
##   06_GWAS_marker_overlap.R
##   07_candidate_gene_annotation.R
##   08_local_ancestry_analysis.R
##   09_LD_analysis.R
##
## Required inputs:
##   results/intermediate/
##     geno_mat_imp_accessionLevel.rds
##     marker_metadata_accessionLevel.rds
##     blup_panel_all_traits.rds
##     ancestry_proxy_500kb_long.rds
##
##   results/tables/
##     GWAS_candidate_intervals_250kb.csv
##     LD_marker_to_lead_all_intervals.csv
##
## Outputs:
##   results/intermediate/
##     haplotype_profile_assignments.rds
##     haplotype_analysis_models.rds
##     sessionInfo_haplotype_analysis.txt
##
##   results/tables/
##     haplotype_markers_used.csv
##     haplotype_profile_assignments.csv
##     haplotype_association_summary.csv
##     haplotype_profile_summary.csv
##     haplotype_profile_carriers.csv
##     favorable_haplotype_profiles.csv
##     candidate_founder_accessions.csv
##
##   results/figures/
##     Fig_LeadSNP_effects_rhizome.png
##     Fig_Haplotype_profile_effects_rhizome.png
##
############################################################

suppressPackageStartupMessages({
  library(dplyr)
  library(tidyr)
  library(ggplot2)
  library(readr)
  library(stringr)
  library(tibble)
  library(purrr)
})

############################################################
## 1. Verify required pipeline objects
############################################################

required_objects <- c(
  "out_intermediate",
  "out_tables",
  "out_figures"
)

missing_objects <- required_objects[
  !vapply(
    required_objects,
    exists,
    logical(1),
    inherits = TRUE
  )
]

if (length(missing_objects) > 0L) {
  stop(
    "Required pipeline objects are missing: ",
    paste(missing_objects, collapse = ", "),
    ". Run 00_setup.R before running this script."
  )
}

############################################################
## 2. Analysis parameters
############################################################

ld_threshold <- 0.50

## Minimum number of accessions required for a profile to be
## included in association testing.

minimum_profile_count <- 3L

## Mean dosage may be fractional because multiple individuals were
## averaged within accessions. For reproducible profile construction,
## values are rounded to the nearest increment below.

dosage_rounding_step <- 0.5

## A region must retain at least this many LD-selected markers.

minimum_markers_per_profile <- 2L

## Number of top profiles retained per region for the descriptive
## favorable-profile table.

top_profiles_per_region <- 2L

############################################################
## 3. Define input files
############################################################

genotype_file <- file.path(
  out_intermediate,
  "geno_mat_imp_accessionLevel.rds"
)

marker_file <- file.path(
  out_intermediate,
  "marker_metadata_accessionLevel.rds"
)

legacy_marker_file <- file.path(
  out_intermediate,
  "gt_filt_accessionLevelMarkers.rds"
)

blup_file <- file.path(
  out_intermediate,
  "blup_panel_all_traits.rds"
)

ancestry_file <- file.path(
  out_intermediate,
  "ancestry_proxy_500kb_long.rds"
)

candidate_interval_file <- file.path(
  out_tables,
  "GWAS_candidate_intervals_250kb.csv"
)

ld_to_lead_file <- file.path(
  out_tables,
  "LD_marker_to_lead_all_intervals.csv"
)

required_files <- c(
  genotype_file,
  blup_file,
  ancestry_file,
  candidate_interval_file,
  ld_to_lead_file
)

missing_files <- required_files[
  !file.exists(required_files)
]

if (length(missing_files) > 0L) {
  stop(
    "The following required files were not found:\n",
    paste(
      missing_files,
      collapse = "\n"
    )
  )
}

if (!file.exists(marker_file)) {
  if (file.exists(legacy_marker_file)) {
    warning(
      "Using legacy marker metadata file: ",
      legacy_marker_file
    )
    marker_file <- legacy_marker_file
  } else {
    stop(
      "Marker metadata file not found. Expected either:\n",
      marker_file,
      "\nor\n",
      legacy_marker_file
    )
  }
}

############################################################
## 4. Load inputs
############################################################

geno_mat <- readRDS(
  genotype_file
)

marker_metadata <- readRDS(
  marker_file
)

blup_panel <- readRDS(
  blup_file
)

ancestry_long <- readRDS(
  ancestry_file
)

candidate_intervals <- read_csv(
  candidate_interval_file,
  show_col_types = FALSE
)

ld_to_lead <- read_csv(
  ld_to_lead_file,
  show_col_types = FALSE
)

geno_mat <- as.matrix(
  geno_mat
)

storage.mode(geno_mat) <- "numeric"

if (is.null(rownames(geno_mat))) {
  stop(
    "The genotype matrix must contain accession IDs as row names."
  )
}

if (anyNA(geno_mat)) {
  stop(
    "Missing values remain in the accession-level genotype matrix."
  )
}

############################################################
## 5. Standardize marker metadata
############################################################

chromosome_candidates <- c(
  "CHR",
  "CHROM",
  "X.CHROM",
  "Chromosome",
  "chromosome"
)

chromosome_column <- intersect(
  chromosome_candidates,
  colnames(marker_metadata)
)

if (length(chromosome_column) == 0L) {
  stop(
    "No chromosome column was found in marker metadata."
  )
}

chromosome_column <- chromosome_column[1]

position_candidates <- c(
  "BP",
  "POS",
  "Position",
  "position"
)

position_column <- intersect(
  position_candidates,
  colnames(marker_metadata)
)

if (length(position_column) == 0L) {
  stop(
    "No physical-position column was found in marker metadata."
  )
}

position_column <- position_column[1]

if ("SNP" %in% colnames(marker_metadata)) {
  marker_metadata$SNP <- as.character(
    marker_metadata$SNP
  )
} else {
  marker_metadata$SNP <- paste0(
    "S",
    marker_metadata[[chromosome_column]],
    "_",
    marker_metadata[[position_column]]
  )
}

marker_metadata$SNP <- make.unique(
  marker_metadata$SNP
)

marker_metadata$CHR <- as.integer(
  marker_metadata[[chromosome_column]]
)

marker_metadata$BP <- as.numeric(
  marker_metadata[[position_column]]
)

############################################################
## 6. Align marker metadata and genotype columns
############################################################

if (
  !is.null(colnames(geno_mat)) &&
    all(colnames(geno_mat) %in% marker_metadata$SNP)
) {

  marker_metadata <- marker_metadata[
    match(
      colnames(geno_mat),
      marker_metadata$SNP
    ),
    ,
    drop = FALSE
  ]

} else if (
  nrow(marker_metadata) == ncol(geno_mat)
) {

  warning(
    "SNP identifiers could not be matched explicitly. ",
    "Marker metadata are being aligned by row order."
  )

  colnames(geno_mat) <- marker_metadata$SNP

} else {

  stop(
    "Marker metadata rows do not match genotype columns."
  )
}

if (
  !identical(
    colnames(geno_mat),
    marker_metadata$SNP
  )
) {
  stop(
    "Marker metadata and genotype columns are not aligned."
  )
}

############################################################
## 7. Validate phenotype columns and align accessions
############################################################

required_blup_columns <- c(
  "Accession",
  "Rhiz_BLUP",
  "Regrowth_BLUP"
)

missing_blup_columns <- setdiff(
  required_blup_columns,
  colnames(blup_panel)
)

if (length(missing_blup_columns) > 0L) {
  stop(
    "BLUP panel is missing required columns: ",
    paste(
      missing_blup_columns,
      collapse = ", "
    )
  )
}

blup_panel$Accession <- as.character(
  blup_panel$Accession
)

common_accessions <- intersect(
  rownames(geno_mat),
  blup_panel$Accession
)

if (length(common_accessions) < 20L) {
  stop(
    "Too few accessions overlap between genotype and BLUP data: ",
    length(common_accessions)
  )
}

common_accessions <- rownames(geno_mat)[
  rownames(geno_mat) %in%
    common_accessions
]

geno_mat <- geno_mat[
  common_accessions,
  ,
  drop = FALSE
]

blup_panel <- blup_panel[
  match(
    common_accessions,
    blup_panel$Accession
  ),
  ,
  drop = FALSE
]

if (
  !identical(
    rownames(geno_mat),
    blup_panel$Accession
  )
) {
  stop(
    "Genotype and BLUP accession orders could not be aligned."
  )
}

############################################################
## 8. Calculate PCA covariates
############################################################

marker_variance <- apply(
  geno_mat,
  2,
  var,
  na.rm = TRUE
)

pca_markers <- is.finite(
  marker_variance
) & marker_variance > 0

if (sum(pca_markers) < 3L) {
  stop(
    "Too few variable markers are available for PCA."
  )
}

pca_fit <- prcomp(
  geno_mat[
    ,
    pca_markers,
    drop = FALSE
  ],
  center = TRUE,
  scale. = TRUE
)

if (ncol(pca_fit$x) < 3L) {
  stop(
    "Fewer than three principal components were produced."
  )
}

pca_scores <- tibble(
  Accession = rownames(
    pca_fit$x
  ),
  PC1 = pca_fit$x[
    ,
    1
  ],
  PC2 = pca_fit$x[
    ,
    2
  ],
  PC3 = pca_fit$x[
    ,
    3
  ]
)

analysis_panel <- blup_panel %>%
  inner_join(
    pca_scores,
    by = "Accession"
  )

############################################################
## 9. Select rhizome-associated intervals and LD markers
############################################################

required_interval_columns <- c(
  "Trait",
  "CHR",
  "GWAS_Interval_ID",
  "GWAS_Lead_SNP",
  "GWAS_Lead_BP",
  "Window_Start",
  "Window_End"
)

missing_interval_columns <- setdiff(
  required_interval_columns,
  colnames(candidate_intervals)
)

if (length(missing_interval_columns) > 0L) {
  stop(
    "Candidate-interval table is missing required columns: ",
    paste(
      missing_interval_columns,
      collapse = ", "
    )
  )
}

rhizome_intervals <- candidate_intervals %>%
  mutate(
    Trait = as.character(Trait),
    CHR = as.integer(CHR),
    GWAS_Interval_ID = as.character(GWAS_Interval_ID),
    GWAS_Lead_SNP = as.character(GWAS_Lead_SNP),
    GWAS_Lead_BP = as.numeric(GWAS_Lead_BP),
    Window_Start = as.numeric(Window_Start),
    Window_End = as.numeric(Window_End)
  ) %>%
  filter(
    str_detect(
      Trait,
      regex(
        "rhiz",
        ignore_case = TRUE
      )
    )
  ) %>%
  distinct(
    GWAS_Interval_ID,
    .keep_all = TRUE
  ) %>%
  arrange(
    CHR,
    GWAS_Lead_BP
  )

if (nrow(rhizome_intervals) == 0L) {
  stop(
    "No rhizome-associated candidate intervals were found."
  )
}

required_ld_columns <- c(
  "Candidate_Interval_ID",
  "Lead_SNP",
  "SNP",
  "BP",
  "R2_to_Lead"
)

missing_ld_columns <- setdiff(
  required_ld_columns,
  colnames(ld_to_lead)
)

if (length(missing_ld_columns) > 0L) {
  stop(
    "Lead-marker LD table is missing required columns: ",
    paste(
      missing_ld_columns,
      collapse = ", "
    )
  )
}

ld_to_lead <- ld_to_lead %>%
  mutate(
    Candidate_Interval_ID =
      as.character(
        Candidate_Interval_ID
      ),
    Lead_SNP =
      as.character(
        Lead_SNP
      ),
    SNP =
      as.character(
        SNP
      ),
    BP =
      as.numeric(
        BP
      ),
    R2_to_Lead =
      as.numeric(
        R2_to_Lead
      )
  )

haplotype_markers <- ld_to_lead %>%
  filter(
    is.finite(
      R2_to_Lead
    ),
    R2_to_Lead >=
      ld_threshold
  ) %>%
  inner_join(
    rhizome_intervals %>%
      select(
        CHR,
        GWAS_Interval_ID,
        GWAS_Lead_SNP,
        GWAS_Lead_BP
      ),
    by = "GWAS_Interval_ID"
  ) %>%
  mutate(
    Is_Lead_SNP =
      SNP ==
      GWAS_Lead_SNP
  ) %>%
  arrange(
    GWAS_Interval_ID,
    desc(
      Is_Lead_SNP
    ),
    desc(
      R2_to_Lead
    ),
    BP
  )

marker_counts <- haplotype_markers %>%
  count(
    GWAS_Interval_ID,
    name =
      "N_Selected_Markers"
  )

valid_intervals <- marker_counts %>%
  filter(
    N_Selected_Markers >=
      minimum_markers_per_profile
  ) %>%
  pull(
    GWAS_Interval_ID
  )

if (length(valid_intervals) == 0L) {
  stop(
    "No interval retained at least ",
    minimum_markers_per_profile,
    " markers at r2 >= ",
    ld_threshold,
    "."
  )
}

haplotype_markers <- haplotype_markers %>%
  filter(
    GWAS_Interval_ID %in%
      valid_intervals
  )

write_csv(
  haplotype_markers,
  file.path(
    out_tables,
    "haplotype_markers_used.csv"
  )
)

############################################################
## 10. Construct multilocus dosage profiles
############################################################

round_to_step <- function(
  x,
  step
) {
  round(
    x /
      step
  ) *
    step
}

format_dosage <- function(x) {
  format(
    x,
    trim = TRUE,
    scientific = FALSE,
    nsmall = 1
  )
}

profile_assignment_list <- list()

for (
  interval_id in
  valid_intervals
) {

  region_markers <- haplotype_markers %>%
    filter(
      GWAS_Interval_ID ==
        interval_id
    ) %>%
    arrange(
      desc(
        Is_Lead_SNP
      ),
      desc(
        R2_to_Lead
      ),
      BP
    )

  selected_snps <- region_markers$SNP

  missing_snps <- setdiff(
    selected_snps,
    colnames(
      geno_mat
    )
  )

  if (length(missing_snps) > 0L) {
    stop(
      "Selected LD markers are missing from the genotype matrix for ",
      interval_id,
      ": ",
      paste(
        missing_snps,
        collapse = ", "
      )
    )
  }

  region_dosage <- geno_mat[
    ,
    selected_snps,
    drop = FALSE
  ]

  rounded_dosage <- round_to_step(
    region_dosage,
    dosage_rounding_step
  )

  profile_string <- apply(
    rounded_dosage,
    1,
    function(x) {
      paste(
        format_dosage(
          x
        ),
        collapse = "|"
      )
    }
  )

  profile_code_lookup <- tibble(
    Profile_String =
      unique(
        profile_string
      )
  ) %>%
    arrange(
      Profile_String
    ) %>%
    mutate(
      Haplotype_Profile =
        paste0(
          "H",
          seq_len(
            n()
          )
        )
    )

  interval_row <- rhizome_intervals %>%
    filter(
      GWAS_Interval_ID ==
        interval_id
    )

  profile_assignment_list[[
    interval_id
  ]] <- tibble(
    Accession =
      rownames(
        region_dosage
      ),
    Candidate_Interval_ID =
      interval_id,
    CHR =
      interval_row$CHR[1],
    Lead_SNP =
      interval_row$GWAS_Lead_SNP[1],
    Lead_BP =
      interval_row$GWAS_Lead_BP[1],
    N_Profile_Markers =
      length(
        selected_snps
      ),
    Profile_String =
      profile_string
  ) %>%
    left_join(
      profile_code_lookup,
      by = "Profile_String"
    )
}

profile_assignments <- bind_rows(
  profile_assignment_list
) %>%
  group_by(
    Candidate_Interval_ID,
    Haplotype_Profile
  ) %>%
  mutate(
    Profile_Count =
      n_distinct(
        Accession
      ),
    Profile_Eligible =
      Profile_Count >=
      minimum_profile_count
  ) %>%
  ungroup() %>%
  arrange(
    CHR,
    Candidate_Interval_ID,
    Haplotype_Profile,
    Accession
  )

saveRDS(
  profile_assignments,
  file.path(
    out_intermediate,
    "haplotype_profile_assignments.rds"
  )
)

write_csv(
  profile_assignments,
  file.path(
    out_tables,
    "haplotype_profile_assignments.csv"
  )
)

############################################################
## 11. Attach phenotypes, PCs, and ancestry-proxy dosage
############################################################

required_ancestry_columns <- c(
  "Accession",
  "Window_ID",
  "CHR",
  "Window_Start",
  "Window_End",
  "Ancestry_Proxy_Dosage"
)

missing_ancestry_columns <- setdiff(
  required_ancestry_columns,
  colnames(
    ancestry_long
  )
)

if (length(missing_ancestry_columns) > 0L) {
  stop(
    "Ancestry-proxy long table is missing required columns: ",
    paste(
      missing_ancestry_columns,
      collapse = ", "
    )
  )
}

interval_ancestry_map <- bind_rows(
  lapply(
    seq_len(
      nrow(
        rhizome_intervals
      )
    ),
    function(interval_index) {

      interval_row <- rhizome_intervals[
        interval_index,
        ,
        drop = FALSE
      ]

      ancestry_long %>%
        filter(
          CHR ==
            interval_row$CHR,
          Window_Start <=
            interval_row$GWAS_Lead_BP,
          Window_End >=
            interval_row$GWAS_Lead_BP
        ) %>%
        transmute(
          Accession,
          Candidate_Interval_ID =
            interval_row$GWAS_Interval_ID,
          Lead_Window_ID =
            Window_ID,
          Lead_Window_Ancestry_Proxy =
            Ancestry_Proxy_Dosage
        )
    }
  )
)

haplotype_panel <- profile_assignments %>%
  left_join(
    analysis_panel %>%
      select(
        Accession,
        Rhiz_BLUP,
        Regrowth_BLUP,
        PC1,
        PC2,
        PC3
      ),
    by = "Accession"
  ) %>%
  left_join(
    interval_ancestry_map,
    by = c(
      "Accession",
      "Candidate_Interval_ID"
    )
  )

############################################################
## 12. Haplotype-profile association tests
############################################################

run_profile_association <- function(
  interval_data,
  trait_column
) {

  model_data <- interval_data %>%
    filter(
      Profile_Eligible,
      is.finite(
        .data[[
          trait_column
        ]]
      ),
      is.finite(
        PC1
      ),
      is.finite(
        PC2
      ),
      is.finite(
        PC3
      )
    ) %>%
    mutate(
      Haplotype_Profile =
        droplevels(
          factor(
            Haplotype_Profile
          )
        )
    )

  n_profiles <- nlevels(
    model_data$Haplotype_Profile
  )

  if (
    nrow(
      model_data
    ) < 10L ||
      n_profiles < 2L
  ) {

    return(
      list(
        summary = tibble(
          Trait =
            trait_column,
          N_Accessions =
            nrow(
              model_data
            ),
          N_Profiles =
            n_profiles,
          Profile_DF =
            NA_real_,
          Residual_DF =
            NA_real_,
          F_Statistic =
            NA_real_,
          P =
            NA_real_,
          Model_R2 =
            NA_real_
        ),
        full_model = NULL,
        reduced_model = NULL
      )
    )
  }

  full_formula <- as.formula(
    paste0(
      trait_column,
      " ~ Haplotype_Profile + PC1 + PC2 + PC3"
    )
  )

  reduced_formula <- as.formula(
    paste0(
      trait_column,
      " ~ PC1 + PC2 + PC3"
    )
  )

  full_model <- lm(
    full_formula,
    data =
      model_data
  )

  reduced_model <- lm(
    reduced_formula,
    data =
      model_data
  )

  comparison <- anova(
    reduced_model,
    full_model
  )

  model_summary <- summary(
    full_model
  )

  list(
    summary = tibble(
      Trait =
        trait_column,
      N_Accessions =
        nrow(
          model_data
        ),
      N_Profiles =
        n_profiles,
      Profile_DF =
        comparison$Df[2],
      Residual_DF =
        df.residual(
          full_model
        ),
      F_Statistic =
        comparison$F[2],
      P =
        comparison$`Pr(>F)`[2],
      Model_R2 =
        model_summary$r.squared
    ),
    full_model =
      full_model,
    reduced_model =
      reduced_model
  )
}

association_rows <- list()
model_objects <- list()

for (
  interval_id in
  valid_intervals
) {

  interval_data <- haplotype_panel %>%
    filter(
      Candidate_Interval_ID ==
        interval_id
    )

  for (
    trait_name in
    c(
      "Rhiz_BLUP",
      "Regrowth_BLUP"
    )
  ) {

    association_result <- run_profile_association(
      interval_data =
        interval_data,
      trait_column =
        trait_name
    )

    result_key <- paste(
      interval_id,
      trait_name,
      sep = "__"
    )

    association_rows[[
      result_key
    ]] <- association_result$summary %>%
      mutate(
        Candidate_Interval_ID =
          interval_id,
        CHR =
          unique(
            interval_data$CHR
          )[1],
        Lead_SNP =
          unique(
            interval_data$Lead_SNP
          )[1],
        Lead_BP =
          unique(
            interval_data$Lead_BP
          )[1],
        .before =
          Trait
      )

    model_objects[[
      result_key
    ]] <- list(
      full_model =
        association_result$full_model,
      reduced_model =
        association_result$reduced_model
    )
  }
}

association_summary <- bind_rows(
  association_rows
) %>%
  group_by(
    Trait
  ) %>%
  mutate(
    FDR_BH =
      p.adjust(
        P,
        method = "BH"
      )
  ) %>%
  ungroup() %>%
  arrange(
    Trait,
    CHR,
    Lead_BP
  )

write_csv(
  association_summary,
  file.path(
    out_tables,
    "haplotype_association_summary.csv"
  )
)

saveRDS(
  model_objects,
  file.path(
    out_intermediate,
    "haplotype_analysis_models.rds"
  )
)

############################################################
## 13. Profile-level descriptive summaries
############################################################

profile_summary <- haplotype_panel %>%
  group_by(
    CHR,
    Candidate_Interval_ID,
    Lead_SNP,
    Lead_BP,
    Haplotype_Profile,
    Profile_String,
    N_Profile_Markers
  ) %>%
  summarise(
    N_Accessions =
      n_distinct(
        Accession
      ),
    Mean_Rhizome_BLUP =
      mean(
        Rhiz_BLUP,
        na.rm = TRUE
      ),
    SD_Rhizome_BLUP =
      sd(
        Rhiz_BLUP,
        na.rm = TRUE
      ),
    Mean_Regrowth_BLUP =
      mean(
        Regrowth_BLUP,
        na.rm = TRUE
      ),
    SD_Regrowth_BLUP =
      sd(
        Regrowth_BLUP,
        na.rm = TRUE
      ),
    Mean_Lead_Window_Ancestry_Proxy =
      mean(
        Lead_Window_Ancestry_Proxy,
        na.rm = TRUE
      ),
    SD_Lead_Window_Ancestry_Proxy =
      sd(
        Lead_Window_Ancestry_Proxy,
        na.rm = TRUE
      ),
    .groups =
      "drop"
  ) %>%
  mutate(
    across(
      c(
        Mean_Rhizome_BLUP,
        SD_Rhizome_BLUP,
        Mean_Regrowth_BLUP,
        SD_Regrowth_BLUP,
        Mean_Lead_Window_Ancestry_Proxy,
        SD_Lead_Window_Ancestry_Proxy
      ),
      ~ifelse(
        is.nan(.x) |
          is.infinite(.x),
        NA_real_,
        .x
      )
    )
  ) %>%
  arrange(
    CHR,
    Candidate_Interval_ID,
    desc(
      Mean_Rhizome_BLUP
    )
  )

write_csv(
  profile_summary,
  file.path(
    out_tables,
    "haplotype_profile_summary.csv"
  )
)

############################################################
## 14. Profile carriers
############################################################

profile_carriers <- haplotype_panel %>%
  group_by(
    CHR,
    Candidate_Interval_ID,
    Haplotype_Profile,
    Profile_String
  ) %>%
  summarise(
    N_Accessions =
      n_distinct(
        Accession
      ),
    Accessions =
      paste(
        sort(
          unique(
            Accession
          )
        ),
        collapse = "; "
      ),
    .groups =
      "drop"
  ) %>%
  arrange(
    CHR,
    Candidate_Interval_ID,
    Haplotype_Profile
  )

write_csv(
  profile_carriers,
  file.path(
    out_tables,
    "haplotype_profile_carriers.csv"
  )
)

############################################################
## 15. Transparently rank descriptive favorable profiles
############################################################

safe_z_score <- function(x) {

  if (
    all(
      !is.finite(
        x
      )
    ) ||
      sd(
        x,
        na.rm = TRUE
      ) == 0
  ) {
    return(
      rep(
        0,
        length(
          x
        )
      )
    )
  }

  as.numeric(
    scale(
      x
    )
  )
}

profile_scored <- profile_summary %>%
  filter(
    N_Accessions >=
      minimum_profile_count
  ) %>%
  group_by(
    Candidate_Interval_ID
  ) %>%
  mutate(
    Z_Rhizome =
      safe_z_score(
        Mean_Rhizome_BLUP
      ),
    Z_Regrowth =
      safe_z_score(
        Mean_Regrowth_BLUP
      ),
    Z_Ancestry_Proxy =
      safe_z_score(
        Mean_Lead_Window_Ancestry_Proxy
      ),
    Descriptive_Profile_Score =
      Z_Rhizome +
      0.5 *
      Z_Regrowth +
      0.5 *
      Z_Ancestry_Proxy
  ) %>%
  ungroup()

favorable_profiles <- profile_scored %>%
  group_by(
    Candidate_Interval_ID
  ) %>%
  slice_max(
    order_by =
      Descriptive_Profile_Score,
    n =
      top_profiles_per_region,
    with_ties =
      FALSE
  ) %>%
  ungroup() %>%
  arrange(
    CHR,
    Candidate_Interval_ID,
    desc(
      Descriptive_Profile_Score
    )
  )

write_csv(
  favorable_profiles,
  file.path(
    out_tables,
    "favorable_haplotype_profiles.csv"
  )
)

############################################################
## 16. Candidate founder-accession ranking
############################################################

candidate_founders <- haplotype_panel %>%
  inner_join(
    favorable_profiles %>%
      select(
        Candidate_Interval_ID,
        Haplotype_Profile,
        Descriptive_Profile_Score
      ),
    by = c(
      "Candidate_Interval_ID",
      "Haplotype_Profile"
    )
  ) %>%
  group_by(
    Accession
  ) %>%
  summarise(
    N_Favorable_Intervals =
      n_distinct(
        Candidate_Interval_ID
      ),
    Favorable_Intervals =
      paste(
        sort(
          unique(
            Candidate_Interval_ID
          )
        ),
        collapse = "; "
      ),
    Mean_Rhizome_BLUP =
      mean(
        Rhiz_BLUP,
        na.rm = TRUE
      ),
    Mean_Regrowth_BLUP =
      mean(
        Regrowth_BLUP,
        na.rm = TRUE
      ),
    Mean_Ancestry_Proxy =
      mean(
        Lead_Window_Ancestry_Proxy,
        na.rm = TRUE
      ),
    Mean_Profile_Score =
      mean(
        Descriptive_Profile_Score,
        na.rm = TRUE
      ),
    .groups =
      "drop"
  ) %>%
  arrange(
    desc(
      N_Favorable_Intervals
    ),
    desc(
      Mean_Rhizome_BLUP
    ),
    desc(
      Mean_Regrowth_BLUP
    ),
    desc(
      Mean_Profile_Score
    )
  ) %>%
  mutate(
    Founder_Rank =
      row_number(),
    .before =
      Accession
  )

write_csv(
  candidate_founders,
  file.path(
    out_tables,
    "candidate_founder_accessions.csv"
  )
)

############################################################
## 17. Lead-SNP effect figure
############################################################

lead_snp_table <- rhizome_intervals %>%
  select(
    CHR,
    Candidate_Interval_ID,
    GWAS_Lead_SNP,
    GWAS_Lead_BP
  )

lead_snp_plot_data <- bind_rows(
  lapply(
    seq_len(
      nrow(
        lead_snp_table
      )
    ),
    function(i) {

      lead_row <- lead_snp_table[
        i,
        ,
        drop = FALSE
      ]

      if (
        !lead_row$GWAS_Lead_SNP %in%
          colnames(
            geno_mat
          )
      ) {
        return(
          NULL
        )
      }

      tibble(
        Accession =
          rownames(
            geno_mat
          ),
        CHR =
          lead_row$CHR,
        Candidate_Interval_ID =
          lead_row$Candidate_Interval_ID,
        Lead_SNP =
          lead_row$GWAS_Lead_SNP,
        Lead_Dosage =
          geno_mat[
            ,
            lead_row$GWAS_Lead_SNP
          ]
      )
    }
  )
) %>%
  left_join(
    analysis_panel %>%
      select(
        Accession,
        Rhiz_BLUP
      ),
    by = "Accession"
  ) %>%
  mutate(
    Rounded_Lead_Dosage =
      factor(
        round_to_step(
          Lead_Dosage,
          dosage_rounding_step
        )
      )
  )

lead_snp_plot <- ggplot(
  lead_snp_plot_data,
  aes(
    x =
      Rounded_Lead_Dosage,
    y =
      Rhiz_BLUP
  )
) +

  geom_boxplot(
    outlier.shape =
      NA
  ) +

  geom_jitter(
    width =
      0.12,
    alpha =
      0.45,
    size =
      1.2
  ) +

  facet_wrap(
    ~Candidate_Interval_ID,
    scales =
      "free_x"
  ) +

  labs(
    title =
      "Rhizome BLUP by GWAS lead-SNP dosage",
    x =
      "Rounded accession-level lead-SNP dosage",
    y =
      "Rhizome BLUP"
  ) +

  theme_classic(
    base_size =
      12
  ) +

  theme(
    plot.title =
      element_text(
        face =
          "bold"
      ),
    strip.text =
      element_text(
        face =
          "bold"
      )
  )

ggsave(
  filename =
    file.path(
      out_figures,
      "Fig_LeadSNP_effects_rhizome.png"
    ),
  plot =
    lead_snp_plot,
  width =
    9,
  height =
    5.5,
  dpi =
    300
)

############################################################
## 18. Multilocus-profile effect figure
############################################################

eligible_plot_data <- haplotype_panel %>%
  filter(
    Profile_Eligible,
    is.finite(
      Rhiz_BLUP
    )
  ) %>%
  mutate(
    Haplotype_Profile =
      factor(
        Haplotype_Profile
      )
  )

if (nrow(eligible_plot_data) > 0L) {

  profile_effect_plot <- ggplot(
    eligible_plot_data,
    aes(
      x =
        Haplotype_Profile,
      y =
        Rhiz_BLUP
    )
  ) +

    geom_boxplot(
      outlier.shape =
        NA
    ) +

    geom_jitter(
      width =
        0.12,
      alpha =
        0.45,
      size =
        1.1
    ) +

    facet_wrap(
      ~Candidate_Interval_ID,
      scales =
        "free_x"
    ) +

    labs(
      title =
        "Rhizome BLUP by local multilocus dosage profile",
      subtitle =
        paste0(
          "Profiles shown only when represented by at least ",
          minimum_profile_count,
          " accessions"
        ),
      x =
        "Operational haplotype profile",
      y =
        "Rhizome BLUP"
    ) +

    theme_classic(
      base_size =
        12
    ) +

    theme(
      plot.title =
        element_text(
          face =
            "bold"
        ),
      strip.text =
        element_text(
          face =
            "bold"
        ),
      axis.text.x =
        element_text(
          angle =
            45,
          hjust =
            1
        )
    )

  ggsave(
    filename =
      file.path(
        out_figures,
        "Fig_Haplotype_profile_effects_rhizome.png"
      ),
    plot =
      profile_effect_plot,
    width =
      10,
    height =
      6,
    dpi =
      300
  )

} else {

  warning(
    "No multilocus profiles met the minimum count for plotting."
  )
}

############################################################
## 19. Save session information
############################################################

writeLines(
  capture.output(
    sessionInfo()
  ),
  file.path(
    out_intermediate,
    "sessionInfo_haplotype_analysis.txt"
  )
)

############################################################
## 20. Completion messages
############################################################

message(
  "10_haplotype_analysis.R completed successfully."
)

message(
  "Intervals analyzed: ",
  length(
    valid_intervals
  )
)

message(
  "Operational haplotype profiles assigned: ",
  n_distinct(
    profile_assignments$Candidate_Interval_ID,
    profile_assignments$Haplotype_Profile
  )
)

message(
  "Association summary saved to: ",
  file.path(
    out_tables,
    "haplotype_association_summary.csv"
  )
)

message(
  "Favorable-profile table saved to: ",
  file.path(
    out_tables,
    "favorable_haplotype_profiles.csv"
  )
)

message(
  "Candidate-founder table saved to: ",
  file.path(
    out_tables,
    "candidate_founder_accessions.csv"
  )
)
