############################################################
##
## S3011 Perennial Sorghum GWAS Pipeline
##
## Script 12: Assemble Manuscript Figures
##
## Purpose:
##   - Verify that figures generated by the analytical scripts
##     are present
##   - Copy and rename selected figures into a single
##     manuscript-ready directory
##   - Create a figure manifest linking manuscript labels to
##     source files and generating scripts
##   - Preserve the original analytical figures unchanged
##
## Important:
##   The analytical scripts generate the figures. This script does
##   not alter the underlying analyses and does not regenerate a
##   missing figure unless rerun_analysis_if_missing is set to TRUE.
##
## Required preceding scripts:
##   00_setup.R
##   01_genotype_QC.R
##   02_aggregate_accession_genotypes.R
##   03_BLUP_estimation.R
##   04_GWAS.R
##   05_marker_based_genome_scan.R
##   06_GWAS_marker_overlap.R
##   07_candidate_gene_annotation.R
##   08_local_ancestry_analysis.R
##   09_LD_analysis.R
##   10_haplotype_analysis.R
##   11_historical_QTL_comparison.R
##
## Outputs:
##   results/manuscript_figures/
##     standardized figure files
##
##   results/tables/
##     manuscript_figure_manifest.csv
##     manuscript_figure_missing_files.csv
##
############################################################

suppressPackageStartupMessages({
  library(dplyr)
  library(readr)
  library(tibble)
})

############################################################
## 1. Verify required pipeline objects
############################################################

required_objects <- c(
  "root_s3011",
  "out_tables",
  "out_figures"
)

missing_objects <- required_objects[
  !vapply(
    required_objects,
    exists,
    logical(1),
    inherits = TRUE
  )
]

if (length(missing_objects) > 0L) {
  stop(
    "Required pipeline objects are missing: ",
    paste(missing_objects, collapse = ", "),
    ". Run 00_setup.R before running this script."
  )
}

############################################################
## 2. User settings
############################################################

## When FALSE, missing figures are reported but no analytical
## scripts are rerun automatically.

rerun_analysis_if_missing <- FALSE

manuscript_figure_dir <- file.path(
  root_s3011,
  "results",
  "manuscript_figures"
)

dir.create(
  manuscript_figure_dir,
  recursive = TRUE,
  showWarnings = FALSE
)

############################################################
## 3. Figure manifest
############################################################

## Edit Manuscript_Label and Destination_File if the final
## manuscript numbering changes.

figure_manifest <- tribble(
  ~Manuscript_Label, ~Description, ~Source_File, ~Generating_Script, ~Destination_File,

  "GWAS_Rhizome",
  "Exploratory GWAS Manhattan plot for rhizome BLUP",
  "GWAS_Rhiz_BLUP_Manhattan.png",
  "04_GWAS.R",
  "Fig_GWAS_Rhizome.png",

  "GWAS_Regrowth",
  "Exploratory GWAS Manhattan plot for overwinter-regrowth BLUP",
  "GWAS_Regrowth_BLUP_Manhattan.png",
  "04_GWAS.R",
  "Fig_GWAS_Regrowth.png",

  "MarkerScan_Rhizome",
  "Complementary marker-based genome scan for rhizome BLUP",
  "marker_scan_Rhiz_BLUP_Manhattan.png",
  "05_marker_based_genome_scan.R",
  "Fig_MarkerScan_Rhizome.png",

  "GWAS_Marker_Overlap",
  "Concordance between GWAS intervals and marker-scan peaks",
  "GWAS_marker_overlap_250kb.png",
  "06_GWAS_marker_overlap.R",
  "Fig_GWAS_Marker_Overlap.png",

  "Ancestry_HighLow",
  "High-minus-low ancestry-proxy contrast for rhizome expression",
  "Fig_AncestryProxy_HighVsLow_Rhizome.png",
  "08_local_ancestry_analysis.R",
  "Fig_Ancestry_HighLow.png",

  "Ancestry_GWAS_Overlay",
  "Ancestry-proxy contrast with GWAS candidate intervals",
  "Fig_AncestryProxy_with_GWASIntervals.png",
  "08_local_ancestry_analysis.R",
  "Fig_Ancestry_GWAS_Overlay.png",

  "Ancestry_Spearman",
  "Spearman association between ancestry proxy and rhizome BLUP",
  "Fig_AncestryProxy_Spearman_Rhizome.png",
  "08_local_ancestry_analysis.R",
  "Fig_Ancestry_Spearman.png",

  "LD_LeadSNP",
  "LD with rhizome GWAS lead SNPs",
  "Fig_LD_to_lead_rhizome_intervals.png",
  "09_LD_analysis.R",
  "Fig_LD_LeadSNP.png",

  "Haplotype_LeadSNP",
  "Rhizome BLUP by lead-SNP dosage",
  "Fig_LeadSNP_effects_rhizome.png",
  "10_haplotype_analysis.R",
  "Fig_LeadSNP_Effects.png",

  "Haplotype_Profile",
  "Rhizome BLUP by local multilocus dosage profile",
  "Fig_Haplotype_profile_effects_rhizome.png",
  "10_haplotype_analysis.R",
  "Fig_Haplotype_Profile_Effects.png",

  "Historical_QTL",
  "Comparison of S3011 candidate intervals with historical perenniality QTL",
  "Fig_Historical_QTL_comparison.png",
  "11_historical_QTL_comparison.R",
  "Fig_Historical_QTL_Comparison.png"
)

############################################################
## 4. Optional analytical script map
############################################################

script_map <- c(
  "04_GWAS.R" =
    file.path(root_s3011, "scripts", "04_GWAS.R"),

  "05_marker_based_genome_scan.R" =
    file.path(root_s3011, "scripts", "05_marker_based_genome_scan.R"),

  "06_GWAS_marker_overlap.R" =
    file.path(root_s3011, "scripts", "06_GWAS_marker_overlap.R"),

  "08_local_ancestry_analysis.R" =
    file.path(root_s3011, "scripts", "08_local_ancestry_analysis.R"),

  "09_LD_analysis.R" =
    file.path(root_s3011, "scripts", "09_LD_analysis.R"),

  "10_haplotype_analysis.R" =
    file.path(root_s3011, "scripts", "10_haplotype_analysis.R"),

  "11_historical_QTL_comparison.R" =
    file.path(root_s3011, "scripts", "11_historical_QTL_comparison.R")
)

############################################################
## 5. Check source figures
############################################################

figure_manifest <- figure_manifest %>%
  mutate(
    Source_Path =
      file.path(
        out_figures,
        Source_File
      ),
    Destination_Path =
      file.path(
        manuscript_figure_dir,
        Destination_File
      ),
    Source_Exists =
      file.exists(
        Source_Path
      )
  )

############################################################
## 6. Optionally rerun generating scripts for missing figures
############################################################

if (
  rerun_analysis_if_missing &&
    any(
      !figure_manifest$Source_Exists
    )
) {

  scripts_to_run <- figure_manifest %>%
    filter(
      !Source_Exists
    ) %>%
    distinct(
      Generating_Script
    ) %>%
    pull(
      Generating_Script
    )

  for (
    script_name in
    scripts_to_run
  ) {

    script_path <- script_map[
      script_name
    ]

    if (
      length(
        script_path
      ) == 0L ||
        is.na(
          script_path
        ) ||
        !file.exists(
          script_path
        )
    ) {

      warning(
        "Generating script was not found: ",
        script_name
      )

      next
    }

    message(
      "Running analytical script to regenerate missing figure(s): ",
      script_name
    )

    source(
      script_path,
      local = new.env(
        parent =
          globalenv()
      )
    )
  }

  figure_manifest <- figure_manifest %>%
    mutate(
      Source_Exists =
        file.exists(
          Source_Path
        )
    )
}

############################################################
## 7. Copy and standardize available figures
############################################################

copy_status <- logical(
  nrow(
    figure_manifest
  )
)

for (
  figure_index in
  seq_len(
    nrow(
      figure_manifest
    )
  )
) {

  if (
    !figure_manifest$Source_Exists[
      figure_index
    ]
  ) {

    copy_status[
      figure_index
    ] <- FALSE

    next
  }

  copy_status[
    figure_index
  ] <- file.copy(
    from =
      figure_manifest$Source_Path[
        figure_index
      ],
    to =
      figure_manifest$Destination_Path[
        figure_index
      ],
    overwrite =
      TRUE,
    copy.mode =
      TRUE,
    copy.date =
      TRUE
  )
}

figure_manifest$Copied_Successfully <-
  copy_status

############################################################
## 8. Record file metadata
############################################################

figure_manifest <- figure_manifest %>%
  rowwise() %>%
  mutate(
    Destination_Exists =
      file.exists(
        Destination_Path
      ),

    Destination_Size_Bytes =
      if (
        Destination_Exists
      ) {
        file.info(
          Destination_Path
        )$size
      } else {
        NA_real_
      },

    Destination_MD5 =
      if (
        Destination_Exists
      ) {
        unname(
          tools::md5sum(
            Destination_Path
          )
        )
      } else {
        NA_character_
      }
  ) %>%
  ungroup()

############################################################
## 9. Save figure manifest and missing-file report
############################################################

write_csv(
  figure_manifest,
  file.path(
    out_tables,
    "manuscript_figure_manifest.csv"
  )
)

missing_figure_report <- figure_manifest %>%
  filter(
    !Source_Exists |
      !Copied_Successfully
  ) %>%
  select(
    Manuscript_Label,
    Description,
    Source_File,
    Source_Path,
    Generating_Script
  )

write_csv(
  missing_figure_report,
  file.path(
    out_tables,
    "manuscript_figure_missing_files.csv"
  )
)

############################################################
## 10. Completion messages
############################################################

message(
  "12_generate_manuscript_figures.R completed."
)

message(
  "Figures listed in manifest: ",
  nrow(
    figure_manifest
  )
)

message(
  "Figures copied successfully: ",
  sum(
    figure_manifest$Copied_Successfully,
    na.rm = TRUE
  )
)

message(
  "Figures missing or not copied: ",
  nrow(
    missing_figure_report
  )
)

message(
  "Manuscript-ready figure directory: ",
  manuscript_figure_dir
)

message(
  "Figure manifest: ",
  file.path(
    out_tables,
    "manuscript_figure_manifest.csv"
  )
)
